### ISSUE TITLE
Overfitting in RND

### ISSUE THREAD

**Issue by KonstiNik** [zincware/ZnNL#63]
When selecting points with RND, the model state gets updated by the final training state, which corresponds to a fit model for the points in the target set. 
After adding a new point to the target set, the whole set is fit again. This means all points are treated similarly during the fit. However, points that were added earlier in the process have passed a huge number of epochs already. 
This means earlier added points run into crazy overfitting. 

Example: 
Always train 50 epochs when adding a point and we want to select 20 points. The first point of the target set will train for 1000 epochs in the end. 

The question is: is that bad? 
We could remove that problem by only training on the new point for N epochs and then training all point for M<<N epochs.

**Comment by SamTov** [comment]
@KonstiNik As above
